---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: mcg-operator-0.1
  namespace: $NAMESPACE
spec:
  displayName: MCG Operator
  install:
    spec:
      deployments:
        - name: test
          spec:
            selector:
              matchLabels:
                app: test
            template:
              metadata:
                labels:
                  app: test
              spec:
                containers:
                  - name: test
    strategy: deployment
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: ocs-operator-0.1
  namespace: $NAMESPACE
spec:
  displayName: OCS Operator
  install:
    spec:
      deployments:
        - name: test
          spec:
            selector:
              matchLabels:
                app: test
            template:
              metadata:
                labels:
                  app: test
              spec:
                containers:
                  - name: test
    strategy: deployment
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: managed-fusion-agent-0.1
  namespace: $NAMESPACE
spec:
  displayName: Managed Fusion Agent
  install:
    spec:
      deployments:
        - name: managed-fusion-controller-manager
          spec:
            selector:
              matchLabels:
                app: test
            template:
              metadata:
                labels:
                  app: test
              spec:
                containers:
                  - name: test
                  - name: kube-rbac-proxy
                    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
    strategy: deployment
---
