apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager-role
subjects:
- kind: ServiceAccount
  name: managed-fusion-agent
  namespace: system
