apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update",]
- apiGroups: [""]
  resources: ["secrets/finalizers"]
  verbs: ["update"]